AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  saveCryptoData:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 63
      Role: 'arn:aws:iam::<changeit>:role/CryptoLambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /savecryptodata
            Method: PUT
      Environment:
        Variables:
          TABLE_NAME: Crypto
